{% set version = "2.13.0" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: litestar-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/litestar/litestar-{{ version }}.tar.gz
  # the SHA256 gets updated by the bot
  sha256: 51a3ab60b7bc8de2c126f3ad907c2ba6f9d22194bdf1be9df52253e57ed80f0e

build:
  # the build number gets reset by the bot
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
  run:
    - python >=3.8

outputs:
  - name: litestar
    build:
      noarch: python
      script:
        - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
      entry_points:
        - litestar = litestar.__main__:run_cli
    requirements:
      host:
        - pip
        - hatchling
        - python >=3.8
      run:
        - annotated-types
        - python >=3.8
        - anyio >=3
        - click
        - exceptiongroup
        - httpx >=0.22
        - importlib-metadata
        - importlib-resources >=5.12.0
        - msgspec >=0.18.2
        - multidict >=6.0.2
        - polyfactory >=2.6.3
        - pyyaml
        - rich >=13.0.0
        - rich-click
        - typing_extensions
    test:
      imports:
        - litestar
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework
      license: MIT
      license_file: LICENSE

  - name: litestar-with-annotated-types
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - annotated-types
    test:
      imports:
        - litestar
        # TODO: import test for annotated-types
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with annotated-types)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-attrs
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - attrs
    test:
      imports:
        - litestar
        - litestar.contrib.attrs
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with attrs)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-brotli
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - brotli
    test:
      imports:
        - litestar
        # TODO: import test for brotli
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with brotli)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-cli
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - jsbeautifier
        - uvicorn-standard
        - uvloop >=0.18.0
    test:
      imports:
        - litestar
        - litestar.cli.main
      commands:
        - pip check
        - litestar --help
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with cli)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-cryptography
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - cryptography
    test:
      imports:
        - litestar
        - litestar.middleware.session.client_side
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with cryptography)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-jinja
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - jinja2 >=3.1.2
    test:
      imports:
        - litestar
        - litestar.contrib.jinja
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with jinja)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-jwt
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - cryptography
        - pyjwt >=2.9.0
    test:
      imports:
        - litestar
        - litestar.contrib.jwt.jwt_token
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with jwt)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-mako
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - mako >=1.2.4
    test:
      imports:
        - litestar
        - litestar.contrib.mako
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with mako)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-minijinja
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - minijinja >=1.0.0
    test:
      imports:
        - litestar
        - litestar.contrib.minijinja
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with minijinja)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-opentelemetry
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - opentelemetry-instrumentation-asgi
    test:
      imports:
        - litestar
        - litestar.contrib.opentelemetry
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with opentelemetry)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-picologging
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - picologging
    test:
      imports:
        - litestar
        - litestar.logging.picologging
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with picologging)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-prometheus
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - prometheus_client
    test:
      imports:
        - litestar
        - litestar.contrib.prometheus
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with prometheus)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-pydantic
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - email-validator
        - pydantic
        - pydantic-extra-types
    test:
      imports:
        - litestar
        - litestar.contrib.pydantic
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with pydantic)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-redis
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - hiredis >=1.0.0
        - redis-py >=4.4.4
    test:
      imports:
        - litestar
        - litestar.stores.redis
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with redis)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-standard
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - fast-query-parsers >=1.0.2
        - jinja2
        - jsbeautifier
        - uvicorn-standard
        - uvloop >=0.18.0
    test:
      imports:
        - litestar
        # TODO: import test for standard
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with standard)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-structlog
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - structlog
    test:
      imports:
        - litestar
        - litestar.middleware.logging
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with structlog)
      license: MIT
      license_file: LICENSE

  - name: litestar-with-full
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("litestar", exact=True) }}
        - {{ pin_subpackage("litestar-with-annotated-types", exact=True) }}
        - {{ pin_subpackage("litestar-with-attrs", exact=True) }}
        - {{ pin_subpackage("litestar-with-brotli", exact=True) }}
        - {{ pin_subpackage("litestar-with-cli", exact=True) }}
        - {{ pin_subpackage("litestar-with-cryptography", exact=True) }}
        - {{ pin_subpackage("litestar-with-jinja", exact=True) }}
        - {{ pin_subpackage("litestar-with-jwt", exact=True) }}
        - {{ pin_subpackage("litestar-with-mako", exact=True) }}
        - {{ pin_subpackage("litestar-with-minijinja", exact=True) }}
        - {{ pin_subpackage("litestar-with-opentelemetry", exact=True) }}
        - {{ pin_subpackage("litestar-with-picologging", exact=True) }}
        - {{ pin_subpackage("litestar-with-prometheus", exact=True) }}
        - {{ pin_subpackage("litestar-with-pydantic", exact=True) }}
        - {{ pin_subpackage("litestar-with-redis", exact=True) }}
        - {{ pin_subpackage("litestar-with-standard", exact=True) }}
        - {{ pin_subpackage("litestar-with-structlog", exact=True) }}
    test:
      requires:
        - pip
      imports:
        - litestar
      commands:
        - pip check
    about:
      home: https://litestar.dev
      dev_url: https://github.com/litestar-org/litestar
      doc_url: https://docs.litestar.dev
      summary: Light-weight and flexible ASGI API Framework (with all extras)
      license: MIT
      license_file: LICENSE

about:
  home: https://litestar.dev
  dev_url: https://github.com/litestar-org/litestar
  doc_url: https://docs.litestar.dev
  summary: Light-weight and flexible ASGI API Framework
  license: MIT
  license_file: LICENSE

extra:
  feedstock-name: litestar
  recipe-maintainers:
    - bollwyvl
    - thewchan
